# File: .github/workflows/docker-publish.yml

name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 3: Build and push Docker image with GitHub run number as tag
      - name: Build and push Docker image with run number tag
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: eilon0723/dental-backend:${{ github.run_number }}
